INSERT INTO MEMBER(USER_NAME,USER_PASSWORD,USER_EMAIL) VALUES ('KING','1234','KING@EMAIL.COM');
INSERT INTO MEMBER(USER_NAME,USER_PASSWORD,USER_EMAIL) VALUES ('KIM','1234','KIM@EMAIL.COM');
INSERT INTO MEMBER(USER_NAME,USER_PASSWORD,USER_EMAIL) VALUES ('EOM','1234','EOM@EMAIL.COM');