DROP TABLE IF EXISTS MEMBER;

CREATE TABLE MEMBER(
    ID               INT             PRIMARY KEY    AUTO_INCREMENT,
    USER_NAME        VARCHAR(255)    NOT NULL,
    USER_PASSWORD    VARCHAR(255)    NOT NULL,
    USER_EMAIL       VARCHAR(255)
);
